[[api]]
name = "get-posts"       # required
method = "get"           # required
route = "v1/based/posts" # required
file = "get-posts.ts"    # required
read = ["database.main"]
write = []               # (default)

[[api]]
name = "post-posts"
method = "post"
route = "v1/based/posts"
file = "post-posts.ts"
write = ["database.main"] # this database will be checked for validity
